### Obtener todas las notas
GET http://localhost:3000/Notes

### Obtener una nota por su id
GET http://localhost:3000/Notes/1

### Obtener una nota por su Categoria
GET http://localhost:3000/Notes/category/Technology

### Obtener una nota por su etiqueta
GET http://localhost:3000/Notes/tags/Tech

### Obteenr una nota por su fecha de creación
GEt http://localhost:3000/Notes/createDate/2021-09-10

### Obtener una nota por su fecha de actualización
GEt http://localhost:3000/Notes/updateDate/2021-09-05

### Crear una nota o blog
POST http://localhost:3000/Notes
Content-Type: application/json

{
  "title": "Startup Success Stories",
  "content": "Inspirational stories from successful entrepreneurs.",
  "category": "Business and Finance",
  "tags": ["Startups", "Entrepreneurship"],
  "createdNotes": "2021-10-25",
  "updatedNotes": "2021-10-25"
}

### Actualizar una nota
PATCH http://localhost:3000/Notes/1
Content-Type: application/json

{
    "title": "The Rise of Social Media",
    "content": "Exploring how social media has changed communication.",
    "category": "Social",
    "tags": ["Social Media", "Trends"],
    "createdNotes": "2021-09-05",
    "updatedNotes": "2021-09-05"
}

### Eliminar una nota
DELETE http://localhost:3000/Notes/1

