### Obtener todas las notas
GET http://localhost:3500/Notes

### Obtener una nota por su id
GET http://localhost:3500/Notes/1

### Obtener una nota por su Categoria
GET http://localhost:3500/Notes/category/Technology

### Obtener una nota por su etiqueta
GET http://localhost:3500/Notes/tags/Tech

### Obteenr una nota por su fecha de creación
GEt http://localhost:3500/Notes/createDate/2021-09-10

### Obtener una nota por su fecha de actualización
GEt http://localhost:3500/Notes/updateDate/2021-09-05

### Crear una nota o blog
POST http://localhost:3500/Notes/Create
Content-Type: application/json

{
  "title": "Mental Health Awareness",
    "content": "Discussing mental health challenges and support.",
    "category": "Social",
    "tags": ["Mental Health", "Wellbeing"],
    "createdNotes": "2021-10-15",
    "updatedNotes": "2021-10-15"
}

### Actualizar una nota
PATCH http://localhost:3500/Notes/1
Content-Type: application/json

{
    "title": "The Rise of Social Media",
    "content": "Exploring how social media has changed communication.",
    "category": "Social",
    "tags": ["Social Media", "Trends"],
    "createdNotes": "2021-09-05",
    "updatedNotes": "2021-09-05"
}

### Eliminar una nota
DELETE http://localhost:3500/Notes/1

